### ISSUE TITLE
It won't run

### ISSUE THREAD

**Issue by Esauromano** [connors/photon#138]
npm start trows 

Uncaught Exception:
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at loadApplicationPackage (/Users/arete/Documents/photon/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/default_app/main.js:257:23)
    at Object.<anonymous> (/Users/arete/Documents/photon/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/default_app/main.js:289:5)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)

**Comment by holywyvern** [comment]
Check pull request #125

**Comment by stevanmilic** [comment]
I had the same problem, first three lines of dist/template-app/app.js should be changed to:

```
// const {app, BrowserWindow} = require('electron')
var app = require('app');
var BrowserWindow = require('browser-window'); 
```
