### ISSUE TITLE
Error on template app

### ISSUE THREAD

**Issue by feavilan04** [connors/photon#162]
We are having an error when running the template app. On menu.js in line 2 console raises the following error "Uncaught TypeError: Cannot destructure property 'Menu' of 'remote' as it is undefined."

**Comment by 1211454975** [comment]
Do you resolve it?

**Comment by 0xtrzy** [comment]
npm start

> proton-template-app@1.0.0 start
> electron .

App threw an error during load
Error: Cannot find module 'app'
Require stack:
- /electron/photon-0.1.2-dist/template-app/app.js
- /electron/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1128)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/electron/photon-0.1.2-dist/template-app/app.js:1:11)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'app'
Require stack:
- /electron/photon-0.1.2-dist/template-app/app.js
- /electron/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1128)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/electron/photon-0.1.2-dist/template-app/app.js:1:11)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)

**Comment by 0xtrzy** [comment]
still trouble
